import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/utils/Header";
import LocationComponent from "@/Components/utils/LocationComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-screen">
      <Header />
      <LocationComponent />
      {children}
    </section>
  );
}
