import type { Metadata } from "next";
import "@/app/cct/globals.css";
import LocationComponent from "@/Components/utils/LocationComponent";
import Headercct from "@/Components/utils/Headercct";
import { cookies } from "next/headers";
export const metadata: Metadata = {
  title: "Counselee ",
  description: "Generated by CC Board Iskcon pune",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authcontent = cookies().get("AUTH")?.value;
  const authparsed = authcontent && JSON.parse(authcontent);
  return (
    <section className="w-screen">
      <Headercct />
      <LocationComponent response={authparsed && authparsed.counselor} />
      {children}
    </section>
  );
}
